config/routes.rb
Rails.application.routes.draw do
    default_url_options :host => "teste-cedro.herokuapp.com"
    resources :disks
    resources :restaurants
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    mount GrapeSwaggerRails::Engine, at: "/documentation"
    mount API::Base, at: "/"
    resources :home

    root to: 'home#index'

end

app/models/disk.rb
class Disk < ApplicationRecord

    acts_as_paranoid

    validates :name, presence: { message: 'Insira o nome do prato' }
    validates :price, presence: { message: 'Insira o preço do prato' }
    
    belongs_to :restaurant, -> {with_deleted}
    
    def self.search(query)
        where("name like ?", "%#{query}%") 
    end

end

app/controllers/api/v1/disks.rb
module API  
    module V1
        class Disks < Grape::API
            
            include API::V1::Defaults

            resource :disks do
                desc "Return disk not deleted"
                params do
                    requires :page, type: String, desc: "page of the 
disks"
                    requires :per_age, type: String, desc: "per-page of the 
disks"
                end

                get "", root: :disks do
                    disks = Disk.without_deleted.order('name ASC').paginate(:page => params[:page], :per_page => params[:per_page])

                end

                desc "Return a disk"
                params do
                    requires :id, type: String, desc: "ID of the 
disk"
                end

                get ":id", root: :disk do
                    Disk.where(id: permitted_params[:id]).without_deleted.first!
                end

                desc "Create a disk"
                params do 
                    requires :restaurant_id, type: Integer, desc: "Id of Restaurant"
                    requires :name, type: String, desc: "Name of the Disk"
                    requires :price, type:Integer, desc: "Price of the Disk"
                end
                post "", root: :disk do
                    @disk = {
                        restaurant_id: params[:restaurant_id],
                        name: params[:name],
                        price: params[:price]
                        }
                    Disk.create(@disk)
                end

                desc "Update a disk",
                params: {
                    "name" => {
                        description: "Name of the disk",
                        required: true,
                        }
                    }
                params do 
                    requires :id, type: String, desc: 'ID of the disk'
                end
                put ":id", root: :disk do

                    disk = Disk.where(id: permitted_params[:id])

                    disk.update({name: params[:name]})

                end

                desc "Deleted a disk"
                params do 
                    requires :id, type: String, desc: 'ID of the disk'
                end
                delete ":id", root: :disk do                    
                    disk = Disk.where(id: permitted_params[:id])
                    disk.update({deleted_at: DateTime.now.to_s})
                end

            end
        end
    end
end  

app/controllers/disks_controller.rb
class DisksController < ApplicationController
    before_action :set_disk, only: [:show, :edit, :update, :destroy]

    # GET /disks
    # GET /disks.json
    def index
        if params[:search]
            @disks = Disk.without_deleted.search(params[:search]).order('name ASC').paginate(:page => params[:page], :per_page => 10)
        else
            @disks = Disk.without_deleted.order('name ASC').paginate(:page => params[:page], :per_page => 10)
        end
    end

    # GET /disks/1
    # GET /disks/1.json
    def show
    end

    # GET /disks/new
    def new
        @disk = Disk.new
    end

    # GET /disks/1/edit
    def edit
    end

    # POST /disks
    # POST /disks.json
    def create
        @disk = Disk.new(disk_params)

        respond_to do |format|
            if @disk.save
                format.html { redirect_to @disk, flash: {:success => 'Prato criado com sucesso.'} }
                format.json { render :show, status: :created, location: @disk }
            else
                format.html { render :new }
                format.json { render json: @disk.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /disks/1
    # PATCH/PUT /disks/1.json
    def update
        respond_to do |format|
            if @disk.update(disk_params)
                format.html { redirect_to @disk, flash: {:success => 'Prato alterado com sucesso.' } }
                format.json { render :show, status: :ok, location: @disk }
            else
                format.html { render :edit }
                format.json { render json: @disk.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /disks/1
    # DELETE /disks/1.json
    def destroy
        @disk.destroy
        respond_to do |format|
            format.html { redirect_to disks_url, flash: { :success => 'Prato desativado com sucesso.'} }
            format.json { head :no_content }
        end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_disk
        @disk = Disk.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def disk_params
        params.require(:disk).permit(:restaurant_id, :name, :price)
    end
end

app/helpers/disks_helper.rb
module DisksHelper
end

app/views/disks/_form.html.erb
<%= bootstrap_form_for @disk do |form| %>

<%= form.collection_select :restaurant_id, Restaurant.all, :id, :name, {prompt: 'Selecione um Restaurante'}, { :multiple => false } %>

<%= form.text_field :name, id: :disk_name, label: 'Prato'  %>

<%= form.text_field :price, id: :disk_price, label: 'Preço' %>

<%= form.submit 'Salvar',class: 'btn btn-primary pull-right' %>

<% end %>
<%= link_to('Cancelar', disks_path, class: 'btn btn-default') %>

app/views/disks/edit.html.erb
<section class="content-header">
    <h1>
        Editar Prato
        <small>Edite o Prato</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href=""><i class="fa fa-dashboard"></i> Home</a></li>
        <li><%= link_to 'Pratos', disks_path %></li>
        <li class="active">Editar Prato</li>
    </ol>
</section>

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-danger">
                <!-- /.box-header -->
                <div class="box-body pad">
                    <%= render 'form', disk: @disk %>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/disks/index.html.erb
<section class="content-header">
    <h1>
        Pratos
        <small>Todas os Pratos</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active"><a href="#">Pratos</a></li>
    </ol>
</section>

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-body">
                    <%= form_tag(disks_path, :method => "get", :class => "form-inline pull-right", id: "search-form", style: "margin-right: 2%") do %>
                    <%= text_field_tag :search, params[:search], placeholder: "Buscar prato", class: "form-control" %>
                    <%= button_tag " ", :name => nil, class: "btn btn-default glyphicon glyphicon-search" %>
                    <% end %>
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Restaurante</th>
                                <th>Prato</th>
                                <th>Preço</th>
                                <th colspan="1"></th>
                            </tr>
                        </thead>
                        <tbody>
                            <% @disks.each do |disk| %>
                            <tr>

                                <td><%= disk.restaurant.name %></td>
                                <td><%= disk.name %></td>
                                <td><%= disk.price %></td>
                                <td><%= link_to '', disk, :class => 'glyphicon glyphicon-eye-open' %></td>
                                <td><%= link_to '', edit_disk_path(disk), :class => 'glyphicon glyphicon-edit', :style => 'color:#FFD600' %></td>
                                <td><%= link_to '', disk, method: :delete, data: { confirm: 'Tem certeza que deseja desativar o prato?' }, :class => 'glyphicon glyphicon-ban-circle', :style => 'color:red' %></td>

                            </tr>
                            <% end %>
                        </tbody>
                    </table>
                    <%= will_paginate @disks, renderer: BootstrapPagination::Rails %>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/disks/new.html.erb
<section class="content-header">
    <h1> Novo Prato
        <small></small>
    </h1>
    <ol class="breadcrumb">
        <li><a href=""><i class="fa fa-dashboard"></i> Home</a></li>
        <li><%= link_to 'Pratos', disks_path %></li>
        <li class="active"><%= link_to 'Novo Prato', new_disk_path %></li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-danger">
                <div class="box-body pad">
                    <%= render 'form', disk: @disk %>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/disks/show.html.erb
<section class="content-header">
    <h1> <%= @disk.name %>
        <small>Cód: <%= @disk.id %></small>
    </h1>
    <ol class="breadcrumb">
        <li><a href=""><i class="fa fa-dashboard"></i> Home</a></li>
        <li><%= link_to 'Prato', disks_path %></li>
        <li class="active"><%= link_to 'Novo Prato', new_disk_path %></li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-danger">
                <div class="box-header">
                    <b> Código: </b> <%= @disk.id %>
                    <div class="pull-right">
                        <%= link_to '', edit_disk_path(@disk), class: 'glyphicon glyphicon-edit', :style => 'color:#FFD600' %>
                        <%= link_to '', @disk, method: :delete, data: { confirm: 'Tem certeza que deseja desativar o restaurante?' }, :class => 'glyphicon glyphicon-ban-circle', :style => 'color:red' %>
                    </div>
                </div>
                <div class="box-body pad">
                    <p><b>Restaurante:  </b>  <%= @disk.restaurant.name %></p>
                    <p><b>Prato:  </b>  <%= @disk.name %></p>
                    <p><b>Preço:  </b>  <%= @disk.price %></p>
                </div>
            </div>
        </div>
    </div>
</section>