config/routes.rb
Rails.application.routes.draw do
    default_url_options :host => "teste-cedro.herokuapp.com"
    resources :disks
    resources :restaurants
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    mount GrapeSwaggerRails::Engine, at: "/documentation"
    mount API::Base, at: "/"
    resources :home

    root to: 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

    <head>
        <title>Teste Cedro</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
    </head>

    <body class="hold-transition skin-blue fixed sidebar-mini">
        <div class="wrapper">

            <header class="main-header">
                <!-- Logo -->
                <a href="#" class="logo">
                    <!-- mini logo for sidebar mini 50x50 pixels -->
                    <span class="logo-mini">
                        <b>TC</b>
                    </span>
                    <!-- logo for regular state and mobile devices -->
                    <span class="logo-lg">
                        <b>Teste Cedro</b>
                    </span>
                </a>
                <!-- Header Navbar: style can be found in header.less -->
                <nav class="navbar navbar-static-top">
                    <!-- Sidebar toggle button-->
                    <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                        <span class="sr-only">Toggle navigation</span>
                    </a>

                    <div class="navbar-custom-menu">
                        <ul class="nav navbar-nav">
                            <!-- Messages: style can be found in dropdown.less-->

                            <!-- User Account: style can be found in dropdown.less -->
                            <li class="dropdown user user-menu">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <%= image_tag('missing.jpg', :class => 'user-image', :alt => 'User Image')%>
                                    <span class="hidden-xs">
                                        Usuário
                                    </span>
                                </a>
                                <ul class="dropdown-menu">
                                    <!-- User image -->
                                    <li class="user-header">
                                        <%= image_tag('missing.jpg', :class => 'img-circle', :alt => 'User Image')%>
                                        <p>
                                            Usuário - Web Developer
                                            <small>Membro desde

                                            </small>
                                        </p>
                                    </li>
                                    <li class="user-footer">
                                        <div class="pull-left">


                                        </div>
                                        <div class="pull-right">

                                        </div>
                                    </li>
                                </ul>
                            </li>
                            <!-- Control Sidebar Toggle Button
<li>
<a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
</li> -->
                        </ul>
                    </div>
                </nav>
            </header>

            <!-- Left side column. contains the logo and sidebar -->
            <aside class="main-sidebar">
                <!-- sidebar: style can be found in sidebar.less -->
                <section class="sidebar">
                    <!-- Sidebar user panel -->
                    <div class="user-panel">
                        <div class="pull-left image">
                            <%= image_tag('missing.jpg', :class => 'img-circle', :alt => 'User Image')%>
                        </div>
                        <div class="pull-left info">
                            <p>
                                <br>
                                Usuário
                            </p>
                            <!--<a href="#"><i class="fa fa-circle text-success"></i> Online</a>-->
                        </div>
                    </div>

                    <!-- sidebar menu: : style can be found in sidebar.less -->
                    <ul class="sidebar-menu tree" data-widget="tree">
                        <li class="header">Menu</li>
                        <!--Dashboard link-->

                        <li class="<%= active_class('/home') %>">
                            <%= link_to '<i class="fa fa-home"></i> <span>Home</span>'.html_safe,  home_index_path %>
                        </li>

                        <li class="treeview  <%= active_class('/restaurants/new') %><%= active_class('/restaurants') %>">
                            <a href="">
                                <i class="fa fa-cutlery"></i>
                                <span>Restaurantes</span>
                                <span class="pull-right-container">
                                    <i class="fa fa-angle-left pull-right"></i>
                                </span>
                            </a>
                            <ul class="treeview-menu active">
          
                                <li class="<%= active_class('/restaurants/new') %>"><%= link_to('<i class="fa fa-circle-o"></i> Adicionar'.html_safe, new_restaurant_path) %></li>
         
                                <li class="<%= active_class('/restaurants') %>"><%= link_to('<i class="fa fa-circle-o"></i> Ver Todos'.html_safe, restaurants_path) %></li>

                            </ul>
                        </li>
                        
                        <li class="treeview  <%= active_class('/disks/new') %><%= active_class('/disks') %>">
                            <a href="">
                                <i class="fa fa-list"></i>
                                <span>Pratos</span>
                                <span class="pull-right-container">
                                    <i class="fa fa-angle-left pull-right"></i>
                                </span>
                            </a>
                            <ul class="treeview-menu active">
          
                                <li class="<%= active_class('/disks/new') %>"><%= link_to('<i class="fa fa-circle-o"></i> Adicionar'.html_safe, new_disk_path) %></li>
         
                                <li class="<%= active_class('/disks') %>"><%= link_to('<i class="fa fa-circle-o"></i> Ver Todos'.html_safe, disks_path) %></li>

                            </ul>
                        </li>

                    </ul>
                </section>
                <!-- /.sidebar -->
            </aside>

            <!-- Content Wrapper. Contains page content -->
            <div class="content-wrapper">
                <div style="margin:10px">
                    <%= render partial: "shared/flash_messages", flash: flash %>
                </div>

                <%= yield %>
                <!-- /.content -->
            </div>
            <!-- /.content-wrapper -->
            <footer class="main-footer">
                <div class="pull-right hidden-xs">
                    <b>Version</b> 0.0.1
                </div>
                <strong>Copyright &copy; 2018
                    <a href="https://vanessasoutoc.ga">Vanessa Souto</a>.</strong> All rights reserved.
            </footer>
        </div>
    </body>

</html>